CREATE TABLE IF NOT EXISTS Players (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    RID VARCHAR(32) NOT NULL,
    Name VARCHAR(100) NOT NULL DEFAULT "",
    Rating INT NOT NULL DEFAULT 0,
    WinCount INT NOT NULL DEFAULT 0,
    LoseCount INT NOT NULL DEFAULT 0,
    ProfilePicture MEDIUMBLOB DEFAULT NULL,
    ProfilePictureExtension VARCHAR(10) DEFAULT ".png",

    KEY (RID)
);
