pub const PACKET_ID_AUTHENTICATION: u32 = 0;
pub const PACKET_ID_ADD_QUEUE: u32 = 1;
pub const PACKET_ID_UPDATE_QUESTION: u32 = 2;
pub const PACKET_ID_QUESTION_ANSWER: u32 = 3;
pub const PACKET_ID_FETCH_LEADERBOARD: u32 = 4;
pub const PACKET_ID_CHANGE_PROFILE_PICTURE: u32 = 5;
pub const PACKET_ID_UPDATE_NAME: u32 = 6;
pub const PACKET_ID_GAME_ENDED: u32 = 7;
pub const PACKET_ID_FETCH_FRIENDS: u32 = 8;
pub const PACKET_ID_FETCH_FRIEND_REQUESTS: u32 = 9;
pub const PACKET_ID_ACCEPT_FRIEND_REQUEST: u32 = 10;
pub const PACKET_ID_DECLINE_FRIEND_REQUEST: u32 = 11;
pub const PACKET_ID_SEARCH_NAME: u32 = 12;
pub const PACKET_ID_ADD_FRIEND_REQUEST: u32 = 13;

